import 'package:flutter/material.dart';
import 'package:dotted_border/dotted_border.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import '../../auth/screens/phone_number.dart';
import '../../../../core/models/vehicle_model.dart';
import '../../../../core/services/garage_service.dart';

class VehicleInfoScreen extends StatefulWidget {
  final bool isRegistration;
  final Vehicle? existingVehicle;
  const VehicleInfoScreen({super.key, this.isRegistration = true, this.existingVehicle});

  @override
  State<VehicleInfoScreen> createState() => _VehicleInfoScreenState();
}

class _VehicleInfoScreenState extends State<VehicleInfoScreen> {
  String? selectedBrand;
  String? selectedModel;
  File? plateImage;
  // Updated for enum compatibility: Car, Motorcycle, Truck, Bus
  String selectedType = 'Car';
  bool _isLoading = false;

  final TextEditingController _plateController = TextEditingController();

  final Color neonGreen = const Color(0xFFCCFF00);

  @override
  void initState() {
    super.initState();
    if (widget.existingVehicle != null) {
      selectedBrand = widget.existingVehicle!.make;
      selectedModel = widget.existingVehicle!.model;
      selectedType = widget.existingVehicle!.type;
      _plateController.text = widget.existingVehicle!.plateNumber;
    }
  }

  @override
  void dispose() {
    _plateController.dispose();
    super.dispose();
  }

  Future<void> _pickImage(ImageSource source) async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: source);
    
    if (image != null) {
      setState(() {
        plateImage = File(image.path);
      });
    }
  }

  void _showImagePickerOptions(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: const Color(0xFF1A1A1A),
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return SafeArea(
          child: Wrap(
            children: [
              ListTile(
                leading: Icon(Icons.photo_library, color: neonGreen),
                title: const Text('Choose from Gallery', style: TextStyle(color: Colors.white)),
                onTap: () {
                  _pickImage(ImageSource.gallery);
                  Navigator.of(context).pop();
                },
              ),
              ListTile(
                leading: Icon(Icons.camera_alt, color: neonGreen),
                title: const Text('Take a Photo', style: TextStyle(color: Colors.white)),
                onTap: () {
                  _pickImage(ImageSource.camera);
                  Navigator.of(context).pop();
                },
              ),
            ],
          ),
        );
      },
    );
  }

  Future<void> _addVehicle() async {
    if (selectedBrand == null || selectedModel == null || _plateController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill all required fields')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      String? photoUrl;
      if (plateImage != null) {
        photoUrl = await GarageService.uploadLicensePlate(plateImage!);
      }

      // Create the vehicle model
      final newVehicle = Vehicle(
        id: '', // Generated by backend
        make: selectedBrand!,
        model: selectedModel!,
        year: 2023,
        plateNumber: _plateController.text,
        color: 'Black',
        type: selectedType, // Use the selected type (Car, Motorcycle, etc.)
        isDefault: true,
        registrationPhotoUrl: photoUrl,
      );

      final result = await GarageService.addVehicle(newVehicle);

      if (result['success']) {
        if (mounted) {
          if (widget.isRegistration) {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => const PhoneNumberScreen(),
              ),
            );
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Vehicle added successfully!')),
            );
            Navigator.pop(context);
          }
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(result['message'] ?? 'Failed to add vehicle')),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _updateVehicle() async {
    if (widget.existingVehicle == null) return;
    if (selectedBrand == null || selectedModel == null || _plateController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all required fields')));
      return;
    }
    setState(() => _isLoading = true);
    try {
      final updatedVehicle = Vehicle(
        id: widget.existingVehicle!.id,
        make: selectedBrand!,
        model: selectedModel!,
        year: widget.existingVehicle!.year,
        plateNumber: _plateController.text,
        color: widget.existingVehicle!.color,
        type: selectedType,
        isDefault: widget.existingVehicle!.isDefault,
        registrationPhotoUrl: widget.existingVehicle!.registrationPhotoUrl,
      );
      final result = await GarageService.updateVehicle(updatedVehicle.id, updatedVehicle);
      if (result['success']) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Vehicle updated successfully!')));
          Navigator.pop(context);
        }
      } else {
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(result['message'] ?? 'Failed to update')));
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _deleteVehicle() async {
    if (widget.existingVehicle == null) return;
    setState(() => _isLoading = true);
    try {
      final result = await GarageService.deleteVehicle(widget.existingVehicle!.id);
      if (result['success']) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Vehicle deleted successfully!')));
          Navigator.pop(context);
        }
      } else {
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(result['message'] ?? 'Failed to delete')));
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          "Vehicle Information", 
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(25.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildLabel("SELECT BRAND/MAKE"),
            _buildDropdown(
              "Choose Brand", 
              ['Toyota', 'BMW', 'Mercedes', 'Hyundai', 'Kia'], 
              selectedBrand, 
              (val) => setState(() => selectedBrand = val)
            ),

            const SizedBox(height: 25),

            _buildLabel("SELECT MODEL"),
            _buildDropdown(
              "Choose Model", 
              ['Corolla', 'X5', 'C-Class', 'Elantra', 'Sportage', 'Lancer', 'Sunny', 'Aveo'], 
              selectedModel, 
              (val) => setState(() => selectedModel = val)
            ),

            const SizedBox(height: 25),

            _buildLabel("VEHICLE TYPE"),
            _buildDropdown(
              "Choose Type", 
              ['Car', 'Motorcycle', 'Truck', 'Bus'], 
              selectedType, 
              (val) => setState(() => selectedType = val!)
            ),

            const SizedBox(height: 25),

            _buildLabel("PLATE NUMBER"),
            TextField(
              controller: _plateController,
              style: const TextStyle(color: Colors.white),
              decoration: _inputDecoration("e.g., ABC 123"),
            ),

            const SizedBox(height: 25),

            _buildLabel("UPLOAD LICENSE PLATE PHOTO"),
            const SizedBox(height: 10),
            
            GestureDetector(
              onTap: () => _showImagePickerOptions(context),
              child: DottedBorder(
                color: neonGreen.withValues(alpha:0.7),
                strokeWidth: 2,
                dashPattern: const [8, 4],
                borderType: BorderType.RRect,
                radius: const Radius.circular(15),
                child: Container(
                  width: double.infinity,
                  height: 180,
                  decoration: BoxDecoration(
                    color: const Color(0xFF0E1108),
                    borderRadius: BorderRadius.circular(15),
                  ),
                  child: plateImage != null
                      ? ClipRRect(
                          borderRadius: BorderRadius.circular(15),
                          child: Image.file(plateImage!, fit: BoxFit.cover),
                        )
                      : Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.camera_alt, color: neonGreen, size: 45),
                            const SizedBox(height: 15),
                            Text(
                              "Tap to capture or upload", 
                              style: TextStyle(color: neonGreen, fontWeight: FontWeight.bold, fontSize: 16)
                            ),
                            const SizedBox(height: 8),
                            const Text(
                              "JPEG, PNG up to 5MB", 
                              style: TextStyle(color: Colors.white38, fontSize: 12)
                            ),
                          ],
                        ),
                ),
              ),
            ),
            const SizedBox(height: 50),
          ],
        ),
      ),
      
      bottomNavigationBar: Padding(
        padding: const EdgeInsets.all(25.0),
        child: widget.isRegistration || widget.existingVehicle == null
            ? ElevatedButton(
                onPressed: _isLoading ? null : _addVehicle,
                style: ElevatedButton.styleFrom(
                  backgroundColor: neonGreen,
                  minimumSize: const Size(double.infinity, 60),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
                ),
                child: _isLoading 
                  ? const CircularProgressIndicator(color: Colors.black)
                  : Text(widget.isRegistration ? "NEXT" : "ADD VEHICLE", style: const TextStyle(color: Colors.black, fontWeight: FontWeight.w900, fontSize: 18)),
              )
            : Row(
                children: [
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : _updateVehicle,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: neonGreen,
                        minimumSize: const Size(double.infinity, 60),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
                      ),
                      child: _isLoading 
                        ? const CircularProgressIndicator(color: Colors.black)
                        : const Text("UPDATE", style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900, fontSize: 16)),
                    ),
                  ),
                  const SizedBox(width: 15),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : _deleteVehicle,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.redAccent,
                        minimumSize: const Size(double.infinity, 60),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
                      ),
                      child: _isLoading 
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text("DELETE", style: TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 16)),
                    ),
                  ),
                ],
              ),
      ),
    );
  }


  Widget _buildLabel(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 10),
    child: Text(
      text, 
      style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.1)
    ),
  );

  Widget _buildDropdown(String hint, List<String> items, String? val, Function(String?) onChanged) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 15),
    decoration: BoxDecoration(
      color: const Color(0xFF0E0E0E),
      borderRadius: BorderRadius.circular(12),
      border: Border.all(color: neonGreen.withValues(alpha:0.3), width: 1.5),
    ),
    child: DropdownButtonHideUnderline(
      child: DropdownButton<String>(
        value: val,
        hint: Text(hint, style: const TextStyle(color: Colors.white24)),
        dropdownColor: const Color(0xFF1A1A1A),
        icon: Icon(Icons.keyboard_arrow_down, color: neonGreen),
        isExpanded: true,
        items: items.map((e) => DropdownMenuItem(
          value: e, 
          child: Text(e, style: const TextStyle(color: Colors.white))
        )).toList(),
        onChanged: onChanged,
      ),
    ),
  );

  InputDecoration _inputDecoration(String hint) => InputDecoration(
    hintText: hint,
    hintStyle: const TextStyle(color: Colors.white12),
    fillColor: const Color(0xFF0E0E0E),
    filled: true,
    contentPadding: const EdgeInsets.all(20),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(12), 
      borderSide: BorderSide(color: neonGreen.withValues(alpha:0.3))
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(12), 
      borderSide: BorderSide(color: neonGreen, width: 2)
    ),
  );
}
